# Generated by Django 5.2.7 on 2025-10-25 16:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FavoriteMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShareableList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "share_hash",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "favorites",
                    models.ManyToManyField(
                        related_name="shared_lists",
                        to="filmes_favoritos_api.favoritemovie",
                    ),
                ),
            ],
        ),
    ]
